### ISSUE TITLE
Add Jump to Line Command

### ISSUE THREAD

**Issue by MarkQueppet** [mrjackphil/obsidian-jump-to-link#33]
It would be very handy if there was one more command that allowed you to jump to the beginning of a specific line. As of now, you cannot navigate to any white space. Combined with the other feature request of #32, this plugin would turn obsidian into a text editing powerhouse. 

Also, awesome work getting this plugin working with live preview!

**Comment by mrjackphil** [comment]
You can put something like `\n` in `jump to regexp` config. It'll show popups - one per line.

**Comment by mrjackphil** [comment]
Feel free to reopen the issue if there are any additional thoughts on that FR.

**Comment by montemartin** [comment]
I've been trying to do this same thing. `\n` is close, but doesn't quite work because the cursor is placed _before_ the matching string so it ends up at the end of the previous line. It does provide jump points for empty lines though.

After a attempting a number of configurations I've found that `.*\n`will give a jump point at the beginning of each line but then no other points on that line are recognized. I still haven't found a way to consistently match the beginning of all lines while still tracking other jump points. Theoretically `^.+?` would work if the `m` (multi-line) flag were set by the plugin.

**Comment by neongreen** [comment]
@montemartin I think I found a way to get beginnings of lines + words:

```
(^|(?<=\n)).|\b\w{3,}\b
```

<img width="509" alt="image" src="https://github.com/user-attachments/assets/07f68c15-aea5-405a-90e1-1ac43f52fdfe">

It matches headings twice (once for the actual beginning of line, once for the first word in the heading), but I suppose it could be fixed with further regex tinkering.
